name: Deploy Next.js to Azure

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: 'ubuntu-latest'
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install node.js
              uses: actions/setup-node@v2
              with:
                node-version: '22'
            
            - name: Install dependencies
              run: npm install

            - name: Build application
              env:
                  AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
                  AUTH_GITHUB_ID: ${{ secrets.AUTH_GITHUB_ID }}
                  AUTH_GITHUB_SECRET: ${{ secrets.AUTH_GITHUB_SECRET }}
                  NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}
                  NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
                  SANITY_WRITE_TOKEN: ${{ secrets.SANITY_WRITE_TOKEN }}
                  NEXT_PUBLIC_SANITY_API_VERSION: ${{ secrets.NEXT_PUBLIC_SANITY_API_VERSION }}
                  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
              run: | 
                npm run build

            - name: Deploy to Azure Web App
              uses: azure/webapps-deploy@v2
              with:
                app-name: 'bloghub'
                publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
                slot: 'Production'
